services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - /Users/shreenathkadam/Documents/embedflow-backend/gateway/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped