worker_processes 1;

events {
    worker_connections 1024;
}

http {

    upstream user_service {
        server host.docker.internal:3001;
    }

    upstream auth_service {
        server host.docker.internal:3002;
    }

    include       mime.types;
    server {
        listen 80;
        server_name localhost;

        location /api/v1/users {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/auth {
            proxy_pass http://auth_service/;
        }
    }
}